### ISSUE TITLE
Code snippets are not visible on Light mode

### ISSUE THREAD

**Issue by fjosue4** [fjosue4/google-gemini-ui#10]
![image](https://github.com/fjosue4/google-gemini-ui/assets/85136931/8d993fd2-52cf-4af9-a016-1cd9a5ded72b)
![image](https://github.com/fjosue4/google-gemini-ui/assets/85136931/dffdec0e-2384-4461-a65e-e8dfd7840e0e)

**Comment by saurabhkacholiya** [comment]
Hi, @fjosue4 I would like to take up this issue can you please assign it to me?

**Comment by fjosue4** [comment]
Sure @saurabhkacholiya thanks for taking it! I'll review your PR shortly!

**Comment by fjosue4** [comment]
I just merged your fix @saurabhkacholiya, thank you for the help!
