### ISSUE TITLE
API Key client side

### ISSUE THREAD

**Issue by natea11** [fjosue4/google-gemini-ui#7]
I am working on a similar project but Google recommends not using the API Key client side.  Do you know of a way to store the API key securely in Google Cloud and send it securely to the client?

Reference:  https://ai.google.dev/gemini-api/docs/get-started/tutorial?lang=web

**Comment by fjosue4** [comment]
Hey @natea11 If you don't want to ask the API to the user directly you could check if using OAuth would provide what you need, the end user will need to sign in using Google and that should be it.

https://ai.google.dev/gemini-api/docs/oauth?hl=es-419

Setting up OAuth could be complicated, at least when I tried implementing it.

**Comment by fjosue4** [comment]
@natea11 Have you had any luck implementing OAuth2.0 to authenticate users instead of asking for the API key?

Just wondering if we could close this issue.

**Comment by natea11** [comment]
I have given up for now.  You can close the issue.  Thanks.
